### ISSUE TITLE
ValueError: cannot reshape array of size 136269 into shape (3,3,1024,1024)

### ISSUE THREAD

**Issue by ManjeeraJagiri** [xslittlegrass/CarND-Vehicle-Detection#12]
When I am running the code, I recieve the following error-
  File "C:\Users\in0131\Downloads\CarND-Vehicle-Detection-master\CarND-Vehicle-Detection-master\utils\utils.py", line 21, in load_weights
    ker = data[index:index+np.prod(kshape)].reshape(kshape)
ValueError: cannot reshape array of size 136269 into shape (3,3,1024,1024)

Any idea on how to proceed?

**Comment by IanBoyanZhang** [comment]
Looks like you are using mismatched pre-trained weight.

**Comment by ManjeeraJagiri** [comment]
I downloaded the wrong set. Thanks a lot!
