### ISSUE TITLE
Different weights file

### ISSUE THREAD

**Issue by subodh-malgonde** [xslittlegrass/CarND-Vehicle-Detection#2]
Hi,

I was having a look at the YOLO V1 website https://pjreddie.com/darknet/yolov1/. It says the `tiny-yolo.weights` file should be around 103 MB. The link provided by you the readme is about 180 MB. Why are these weight files different?

Also you have provided a reference to `https://github.com/sunshineatnoon/Darknet.keras` in your utils file. The model architecture in that repository seems to be different than yours, both are supposed to be for YOLO v1. The `Darknet.keras` repo doesn't have leaky relu after every convolutional layer, but yours does. Why is that so?

Thanks,
Subodh

**Comment by xslittlegrass** [comment]
Hi Subodh,

The 103MB file is for the version 1.1, which has a different architecture.
If you see the `RunTinyYOLO.py` in `Darkent.keras`, you will see that it does include leaky relus.

**Comment by subodh-malgonde** [comment]
Thanks!

**Comment by subodh-malgonde** [comment]
~~So which is your architecture, 1.0 or something else? Can you give me a link to the research paper for your YOLO architecture?~~

Figured it out.
