### ISSUE TITLE
would you provide the trainning method

### ISSUE THREAD

**Issue by zchky** [xslittlegrass/CarND-Vehicle-Detection#8]
there are some problems on re-train this network, would you post your method?

**Comment by 2017develper** [comment]
is it run in windows 10 ????

**Comment by xslittlegrass** [comment]
@zchky This project uses pretrained weights, and the training is not available. I'll try to update the training method when I get time to work on this. Thanks.

**Comment by xslittlegrass** [comment]
@2017develper It should run in windows 10 as long as you have Python and keras installed.
